openapi: "3.1.0"
info:
  title: Activities service
  version: v1
servers:
  - url: https://{domain}.uspacy.ua
    description: Ukrainian server
  - url: https://{domain}.uspacy.eu
    description: EU server
  - url: https://{domain}.uspacy.com.br
    description: Brazilian server
  - url: https://{domain}.uspacy.com
    description: International server
tags:
  - name: activities
paths:
  /activities/v1/activities:
    get:
      tags:
        - activities
      summary: Get activities list
      parameters:
        - name: responsible_id
          in: query
          schema:
            type: array
            items:
              type: integer
        - name: title
          in: query
          schema:
            type: string
        - $ref: "#/components/parameters/list"
        - $ref: "#/components/parameters/page"
        - name: params
          in: query
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                type: integer
          style: form
          explode: true
          example:
            leads[]: 1
            companies[]: 23
            contacts[]: 41
        - name: id
          in: query
          schema:
            type: array
            items:
              type: integer
        - name: start_time
          in: query
          schema:
            type: array
            items:
              type: array
              items:
                type: integer
        - name: type
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ActivityType"
        - name: priority
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ActivityPriority"
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/ActivityStatus"
        - name: boolean_operator
          in: query
          schema:
            type: string
            enum:
              - AND
              - OR
        - name: old_filter
          in: query
          schema:
            type: boolean
        - name: sort_by
          in: query
          schema:
            type: object
            additionalProperties:
              type: string
              enum:
                - desc
                - asc
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Activity"
                  - type: object
                    properties:
                      meta:
                        $ref: "#/components/schemas/Meta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      security:
        - bearerAuth: []
    post:
      tags:
        - activities
      summary: Create activity
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - required:
                    - title
                    - start_time
                    - end_time
                - $ref: "#/components/schemas/CreateOrUpdateActivity"
                - type: object
                  properties:
                    created_by:
                      type: integer
                    created_at:
                      type: integer
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/Forbidden"
        "422":
          $ref: "#/components/responses/ValidationError"
      security:
        - bearerAuth: []
  /activities/v1/activities/{activityId}:
    parameters:
      - $ref: "#/components/parameters/activityId"
    get:
      tags:
        - activities
      summary: Show activity
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
      security:
        - bearerAuth: []
    patch:
      tags:
        - activities
      summary: Update activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrUpdateActivity"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/ValidationError"
      security:
        - bearerAuth: []
    delete:
      tags:
        - activities
      summary: Delete activity by id
      responses:
        "204":
          description: No content
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
      security:
        - bearerAuth: []
  /activities/v1/activities/mass_deletion:
    delete:
      tags:
        - activities
      summary: Bulk deletion activities
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MassActionActivity"
      responses:
        "204":
          description: No content
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/Forbidden"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  text:
                    type: array
                    items:
                      example: "Forbidden message"
              status:
                type: boolean
                example: true
    NoContent:
      description: No Content
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    ValidationError:
      description: Validation error response
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  field_name: ["The field_name field is required."]
              status:
                type: boolean
                example: true
  parameters:
    activityId:
      in: path
      name: activityId
      schema:
        type: integer
        format: int64
      required: true
      description: Activity ID
    page:
      name: page
      in: query
      description: current page
      required: false
      schema:
        type: integer
        default: 1
      example: 1
    list:
      name: list
      in: query
      description: how many items should be per page
      required: false
      schema:
        type: integer
        default: 20
      example: 10
  schemas:
    Meta:
      type: object
      properties:
        currentPage:
          type: integer
          example: 1
        from:
          type: integer
          example: 1
        lastPage:
          type: integer
          example: 1
        links:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                example: null
              label:
                type: string
                example: "Previous"
              active:
                type: boolean
                example: false
        path:
          type: string
          example: "https://domain.uspacy.ua/groups/v1/groups"
        perPage:
          type: integer
          example: 20
        to:
          type: integer
          example: 2
        total:
          type: integer
          example: 2
    ActivityStatus:
      type: string
      enum:
        - planned
        - done
        - cancelled
    ActivityType:
      type: string
      enum:
        - activity
        - call
        - meeting
        - chat
        - email
    ActivityPriority:
      type: string
      enum:
        - low
        - notHigh
        - neutral
        - high
        - veryHigh
    ActivityCrmEntities:
      type: object
      additionalProperties:
        type: array
        items:
          type: object
          required:
            - id
            - title
            - owner
          properties:
            id:
              type: integer
            title:
              type: string
            owner:
              type: integer
    Activity:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        type:
          $ref: "#/components/schemas/ActivityType"
        status:
          $ref: "#/components/schemas/ActivityStatus"
        priority:
          $ref: "#/components/schemas/ActivityPriority"
        description:
          type: string
        start_time:
          type: integer
        end_time:
          type: integer
        responsible_id:
          type: integer
        company_id:
          type: integer
        created_at:
          type: integer
        updated_at:
          type: integer
        closed_by:
          type:
            - integer
            - "null"
        first_closed_by:
          type:
            - integer
            - "null"
        closed_at:
          type:
            - integer
            - "null"
        first_closed_at:
          type:
            - integer
            - "null"
        participants:
          type: array
          items:
            type: integer
        crm_entities:
          $ref: "#/components/schemas/ActivityCrmEntities"
    CreateOrUpdateActivity:
      type: object
      properties:
        title:
          type: string
        type:
          $ref: "#/components/schemas/ActivityType"
        status:
          $ref: "#/components/schemas/ActivityStatus"
        priority:
          $ref: "#/components/schemas/ActivityPriority"
        description:
          type: string
        start_time:
          type: integer
        end_time:
          type: integer
        responsible_id:
          type: integer
        company_id:
          type: integer
        participants:
          type: array
          items:
            type: integer
        crm_entities:
          $ref: "#/components/schemas/ActivityCrmEntities"
    MassActionActivity:
      oneOf:
        - type: object
          required:
            - all
          properties:
            all:
              type: boolean
              default: true
            except_ids:
              type: array
              items:
                type: integer
        - type: object
          required:
            - entity_ids
          properties:
            entity_ids:
              type: array
              items:
                type: integer
