name: ReadMe GitHub Action Validate 🦉

on:
  pull_request:

jobs:
  rdme-openapi-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Validate api.yml 🚀
        uses: readmeio/rdme@v9.0.3
        with:
          rdme: openapi validate schemas/api.yml

      - name: Validate commentsService.yml 🚀
        uses: readmeio/rdme@v9.0.3
        with:
          rdme: openapi validate schemas/commentsService.yml

      - name: Validate newsFeedService.yml 🚀
        uses: readmeio/rdme@v9.0.3
        with:
          rdme: openapi validate schemas/newsFeedService.yml

      - name: Validate messenger.yml 🚀
        uses: readmeio/rdme@v9.0.3
        with:
          rdme: openapi validate schemas/messenger.yml
